version: "3.9"

services:
  # -----------------------
  # PostgreSQL для Auth
  # -----------------------
  auth-postgres:
    image: postgres:15
    container_name: auth-service-db
    restart: always
    environment:
      POSTGRES_DB: auth_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - auth-users:/var/lib/postgresql/data
    networks:
      - backend-network

  # -----------------------
  # PostgreSQL для Users
  # -----------------------
  users-postgres:
    image: postgres:15
    container_name: users-service-db
    restart: always
    environment:
      POSTGRES_DB: user_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - users:/var/lib/postgresql/data
    networks:
      - backend-network

  # -----------------------
  # PostgreSQL для Content
  # -----------------------
  content-postgres:
    image: postgres:15
    container_name: content-service-db
    restart: always
    environment:
      POSTGRES_DB: content_service_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - content:/var/lib/postgresql/data
    networks:
      - backend-network

  # -----------------------
  # Kafka для сервисов
  # -----------------------
  kafka-users-service:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-users-service:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka-users-service:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
      - KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=0
    networks:
      - backend-network

  # -----------------------
  # Auth-service
  # -----------------------
  auth-service:
    image: auth-user-service:0.0.1
    container_name: auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://auth-postgres:5432/auth_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    depends_on:
      - auth-postgres
      - kafka-users-service
    ports:
      - "7070:7070"
    networks:
      - backend-network

  # -----------------------
  # Users-service
  # -----------------------
  users-service:
    image: users-service:0.0.1
    container_name: users-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://users-postgres:5432/user_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-users-service:9092
    depends_on:
      - users-postgres
      - kafka-users-service
    ports:
      - "8080:8080"
    networks:
      - backend-network

  # -----------------------
  # Content-service
  # -----------------------
  content-service:
    image: content-service:0.0.1
    container_name: content-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://content-postgres:5432/content_service_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka-users-service:9092
    depends_on:
      - content-postgres
      - kafka-users-service
    ports:
      - "8081:8080"
    networks:
      - backend-network

  # -----------------------
  # Minio (один для всех сервисов)
  # -----------------------
  minio:
    image: quay.io/minio/minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
    networks:
      - backend-network

  # -----------------------
  # PgAdmin для всех баз
  # -----------------------
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "9090:80"
    depends_on:
      - auth-postgres
      - users-postgres
      - content-postgres
    networks:
      - backend-network

# -----------------------
# Сети и тома
# -----------------------
networks:
  backend-network:
    driver: bridge

volumes:
  auth-users:
  users:
  content:
  minio-data:
